version: "3.7"
services:
  web:
    image: nginx:1.16-alpine
    container_name: g-ngx
    volumes:
      - ./nginx/nginx-gunicorn.conf:/tmp/nginx.conf
    command: sh -c "envsubst < /tmp/nginx.conf > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    networks:
      - flk-ngx-g
    ports:
      - 8000:80
    depends_on:
      - backend
  backend:
    build:
      context: ./app
      dockerfile: Dockerfile.gunicorn
    container_name: g-flk
    networks:
      - flk-ngx-g
    expose:
      - 8000
networks:
  flk-ngx-g:
    driver: bridge